export const products = [
    { id: 1,
        name: "Stencil strike shorts",
        price: 1990,
        image: "media/images/catalog/img1.png",
        description: 'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.   Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.',
        details: ['Part of our responsible edit.','Plain design','Crew neck', 'Short sleeves', 'Regular fit', 'True to sizes'],
        detail_photo: ["media/images/catalog/catalog_info/img1_front.png", "media/images/catalog/catalog_info/img1_back.png"],
        sizes: [ 'L'],
        colors: ['#ffffff', '#000000', '#375FED', '#D60000'],
        types: ["Shorts"],
        categories: ["Training"]
    },
    { id: 2,
        name: "Stencil strike shorts",
        price: 2990, image: "media/images/catalog/img2.png",
        description: 'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.   Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.',
        details: ['Part of our responsible edit.','Plain design','Crew neck', 'Short sleeves', 'Regular fit', 'True to sizes'],
        detail_photo: ["media/images/catalog/catalog_info/img1_front.png", "media/images/catalog/catalog_info/img1_back.png"],
        sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        colors: ['#ffffff', '#000000', '#375FED', '#D60000'],
        types: ["Shorts"],
        categories: ["Training"]
    },
    { id: 3,
        name: "Stencil strike shorts",
        price: 3990,
        image: "media/images/catalog/img3.png",
        description: 'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.   Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.',
        details: ['Part of our responsible edit.','Plain design','Crew neck', 'Short sleeves', 'Regular fit', 'True to sizes'],
        detail_photo: ["media/images/catalog/catalog_info/img1_front.png", "media/images/catalog/catalog_info/img1_back.png"],
        sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        colors: ['#ffffff', '#000000', '#375FED', '#D60000'],
        types: ["Shorts"],
        categories: ["Training"]
    },
    { id: 4,
        name: "Stencil strike shorts",
        price: 4990,
        image: "media/images/catalog/img4.png",
        description: 'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.   Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.',
        details: ['Part of our responsible edit.','Plain design','Crew neck', 'Short sleeves', 'Regular fit', 'True to sizes'],
        detail_photo: ["media/images/catalog/catalog_info/img1_front.png", "media/images/catalog/catalog_info/img1_back.png"],
        sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        colors: ['#ffffff', '#000000', '#375FED', '#D60000'],
        types: ["Shorts"],
        categories: ["Training"]
    },
    { id: 5,
        name: "Stencil strike shorts",
        price: 5990,
        image: "media/images/catalog/img5.png",
        description: 'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.   Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.',
        details: ['Part of our responsible edit.','Plain design','Crew neck', 'Short sleeves', 'Regular fit', 'True to sizes'],
        detail_photo: ["media/images/catalog/catalog_info/img1_front.png", "media/images/catalog/catalog_info/img1_back.png"],
        sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        colors: ['#ffffff', '#000000', '#375FED', '#D60000'],
        types: ["Shorts"],
        categories: ["Training"]
    },
    { id: 6,
        name: "Stencil strike shorts",
        price: 6990,
        image: "media/images/catalog/img6.png",
        description: 'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.   Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.',
        details: ['Part of our responsible edit.','Plain design','Crew neck', 'Short sleeves', 'Regular fit', 'True to sizes'],
        detail_photo: ["media/images/catalog/catalog_info/img1_front.png", "media/images/catalog/catalog_info/img1_back.png"],
        sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        colors: ['#ffffff', '#000000', '#375FED', '#D60000'],
        types: ["Shorts"],
        categories: ["Training"]
    },
    { id: 7,
        name: "Stencil strike shorts",
        price: 7990,
        image: "media/images/catalog/img7.png",
        description: 'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.   Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.',
        details: ['Part of our responsible edit.','Plain design','Crew neck', 'Short sleeves', 'Regular fit', 'True to sizes'],
        detail_photo: ["media/images/catalog/catalog_info/img1_front.png", "media/images/catalog/catalog_info/img1_back.png"],
        sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        colors: ['#ffffff', '#000000', '#375FED', '#D60000'],
        types: ["Shorts"],
        categories: ["Training"]
    },
    { id: 8,
        name: "Stencil strike shorts",
        price: 8990,
        image: "media/images/catalog/img8.png",
        description: 'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.   Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.',
        details: ['Part of our responsible edit.','Plain design','Crew neck', 'Short sleeves', 'Regular fit', 'True to sizes'],
        detail_photo: ["media/images/catalog/catalog_info/img1_front.png", "media/images/catalog/catalog_info/img1_back.png"],
        sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        colors: ['#ffffff', '#000000', '#375FED', '#D60000'],
        types: ["Shorts"],
        categories: ["Training"]
    },
    { id: 9,
        name: "Stencil strike shorts",
        price: 9990,
        image: "media/images/catalog/img9.png",
        description: 'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.   Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.',
        details: ['Part of our responsible edit.','Plain design','Crew neck', 'Short sleeves', 'Regular fit', 'True to sizes'],
        detail_photo: ["media/images/catalog/catalog_info/img1_front.png", "media/images/catalog/catalog_info/img1_back.png"],
        sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        colors: ['#ffffff', '#000000', '#375FED', '#D60000'],
        types: ["Shorts"],
        categories: ["LifeStyle"]
    },
    { id: 10,
        name: "Stencil strike shorts",
        price: 4990,
        image: "media/images/catalog/img10.png",
        description: 'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.   Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.',
        details: ['Part of our responsible edit.','Plain design','Crew neck', 'Short sleeves', 'Regular fit', 'True to sizes'],
        detail_photo: ["media/images/catalog/catalog_info/img1_front.png", "media/images/catalog/catalog_info/img1_back.png"],
        sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        colors: ['#ffffff', '#000000', '#375FED', '#D60000'],
        types: ["Shorts"],
        categories: ["Training"]
    },
    { id: 11,
        name: "Stencil strike shorts",
        price: 2990,
        image: "media/images/catalog/img11.png",
        description: 'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.   Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.',
        details: ['Part of our responsible edit.','Plain design','Crew neck', 'Short sleeves', 'Regular fit', 'True to sizes'],
        detail_photo: ["media/images/catalog/catalog_info/img1_front.png", "media/images/catalog/catalog_info/img1_back.png"],
        sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        colors: ['#ffffff', '#000000', '#375FED', '#D60000'],
        types: ["Shorts"],
        categories: ["LifeStyle"]
    },
    { id: 12,
        name: "Stencil strike shorts",
        price: 4990,
        image: "media/images/catalog/img12.png",
        description: 'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.   Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.',
        details: ['Part of our responsible edit.','Plain design','Crew neck', 'Short sleeves', 'Regular fit', 'True to sizes'],
        detail_photo: ["media/images/catalog/catalog_info/img1_front.png", "media/images/catalog/catalog_info/img1_back.png"],
        sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        colors: ['#ffffff', '#000000', '#375FED', '#D60000'],
        types: ["Shorts"],
        categories: ["Training"]
    },
    { id: 13,
        name: "Stencil strike shorts",
        price: 3990,
        image: "media/images/catalog/img13.png",
        description: 'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.   Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.',
        details: ['Part of our responsible edit.','Plain design','Crew neck', 'Short sleeves', 'Regular fit', 'True to sizes'],
        detail_photo: ["media/images/catalog/catalog_info/img1_front.png", "media/images/catalog/catalog_info/img1_back.png"],
        sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        colors: ['#ffffff', '#000000', '#375FED', '#D60000'],
        types: ["Shorts"],
        categories: ["Training"]
    },
    { id: 14,
        name: "Stencil strike shorts",
        price: 5990,
        image: "media/images/catalog/img14.png",
        description: 'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.   Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.',
        details: ['Part of our responsible edit.','Plain design','Crew neck', 'Short sleeves', 'Regular fit', 'True to sizes'],
        detail_photo: ["media/images/catalog/catalog_info/img1_front.png", "media/images/catalog/catalog_info/img1_back.png"],
        sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        colors: ['#ffffff', '#000000', '#375FED', '#D60000'],
        types: ["Shorts"],
        categories: ["Training"]

    },
    { id: 15,
        name: "Stencil strike shorts",
        price: 8990,
        image: "media/images/catalog/img15.png",
        description: 'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.   Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.',
        details: ['Part of our responsible edit.','Plain design','Crew neck', 'Short sleeves', 'Regular fit', 'True to sizes'],
        detail_photo: ["media/images/catalog/catalog_info/img1_front.png", "media/images/catalog/catalog_info/img1_back.png"],
        sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        colors: ['#ffffff', '#000000', '#375FED', '#D60000'],
        types: ["Hoddies"],
        categories: ["LifeStyle"]
    },
]; 